# Generated by Django 4.2.5 on 2023-10-13 07:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(blank=True, max_length=32)),
                ('currency_code', models.CharField(default='KZT', max_length=3)),
                ('deposited_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('holding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('locked_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
