# Generated by Django 4.2.5 on 2023-10-18 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INCOMING', 'Входящие средства'), ('OUTGOING', 'Исходящие средства'), ('HOLDING', 'Замороженные средства'), ('LOCKED', 'Заблокированные средства')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_number', models.TextField(null=True)),
                ('payment_type', models.CharField(choices=[('BANK_TRANSFER', 'Безналичный перевод'), ('CASH_PAYMENT', 'Наличные')], max_length=32, null=True)),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=32)),
                ('contract_number', models.CharField(max_length=512, null=True)),
                ('currency_code', models.CharField(default='KZT', max_length=3)),
                ('deposited_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('holding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('locked_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('funds', models.ManyToManyField(blank=True, to='wallets.fund')),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
