# Generated by Django 4.2.5 on 2023-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='platform',
            field=models.CharField(choices=[('DVA', 'DVA'), ('STD', 'STD')], default='DVA', max_length=32),
        ),
        migrations.AlterField(
            model_name='fund',
            name='payment_type',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Безналичный перевод'), ('CASH_PAYMENT', 'Наличные')], default='BANK_TRANSFER', max_length=32),
        ),
    ]
