# Generated by Django 4.2.5 on 2023-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_fund_wallet_delete_mainwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='funds',
            field=models.ManyToManyField(blank=True, to='wallets.fund'),
        ),
    ]
