# Generated by Django 4.2.5 on 2023-10-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='payment_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='payment_type',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Безналичный перевод'), ('CASH_PAYMENT', 'Наличные')], max_length=32, null=True),
        ),
    ]
