# Generated by Django 4.2.5 on 2023-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAIN_WALLET', 'Основной счет'), ('SUB_WALLET', 'Доп счет')], max_length=12)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
