# Generated by Django 4.2.5 on 2023-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70)),
                ('event', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('SEND_CODE', 'SEND_CODE')], max_length=12)),
                ('method', models.CharField(choices=[('telegram', 'telegram')], max_length=12)),
                ('code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('embeded', models.BooleanField(default=False)),
                ('cert', models.TextField()),
            ],
        ),
    ]
