# Generated by Django 4.2.5 on 2023-10-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='bank_account',
            new_name='bank_accounts',
        ),
    ]
